image: java:8-jdk

stages:
  - build
  - test
  - staging
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
      - '**/*.gradle'
      - src/**/*
      when: always

checkstyle:
  stage: build
  script:
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_TAG
      when: never
    - changes:
      - '**/*.gradle'
      - src/**/*
      - config/checkstyle/**/*
      when: always

test:
  stage: test
  coverage: '/Total.*?(\d+)%/'
  script:
    - ./gradlew test --info -PexcludeTests=**/RastreioTest.class
    - ./gradlew jacocoTestReport
    - cat build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_TAG
      when: on_success
    - changes:
      - '**/*.gradle'
      - src/**/*
      when: on_success

staging:
  stage: staging
  script:
    - ./gradlew test --info -PincludeTests=**/RastreioTest.class
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_TAG
      when: on_success
    - changes:
      - '**/*.gradle'
      - src/**/*
      when: on_success

checkpublish:
  stage: staging
  script:
    - ./gradlew publishToMavenLocal
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: manual

publish:
  stage: publish
  script:
    - ./gradlew publish
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never

# TODO: publish to gh-pages
