package rastreio;

/**
 * Inferred tracking object service type from object code.
 * @see <a href="https://www.correios.com.br/enviar-e-receber/precisa-de-ajuda/siglas-utilizadas-no-rastreamento-de-objeto"></a>
 */
public enum TrackObjectServiceType {
  /**
   * AA - ETIQUETA LÓGICA SEDEX.
   */
  AA("AA", "ETIQUETA LÓGICA SEDEX"),
  /**
   * AB - ETIQUETA LÓGICA SEDEX.
   */
  AB("AB", "ETIQUETA LÓGICA SEDEX"),
  /**
   * AL - AGENTES DE LEITURA.
   */
  AL("AL", "AGENTES DE LEITURA"),
  /**
   * AR - AVISO DE RECEBIMENTO.
   */
  AR("AR", "AVISO DE RECEBIMENTO"),
  /**
   * AS - ENCOMENDA PAC - ACAO SOCIAL.
   */
  AS("AS", "ENCOMENDA PAC - ACAO SOCIAL"),
  /**
   * BE - REMESSA ECONÔMICA S/ AR DIGITAL.
   */
  BE("BE", "REMESSA ECONÔMICA S/ AR DIGITAL"),
  /**
   * BF - REMESSA EXPRESSA S/ AR DIGITAL.
   */
  BF("BF", "REMESSA EXPRESSA S/ AR DIGITAL"),
  /**
   * BG - ETIQUETA LOG REM ECON C/AR BG.
   */
  BG("BG", "ETIQUETA LOG REM ECON C/AR BG"),
  /**
   * BH - MENSAGEM FÍSICO-DIGITAL.
   */
  BH("BH", "MENSAGEM FÍSICO-DIGITAL"),
  /**
   * BI - ETIQUETA LÓG REGIST URG.
   */
  BI("BI", "ETIQUETA LÓG REGIST URG"),
  /**
   * CA - OBJETO INTERNACIONAL COLIS.
   */
  CA("CA", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CB - OBJETO INTERNACIONAL COLIS.
   */
  CB("CB", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CC - OBJETO INTERNACIONAL COLIS.
   */
  CC("CC", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CD - OBJETO INTERNACIONAL COLIS.
   */
  CD("CD", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CE - OBJETO INTERNACIONAL COLIS.
   */
  CE("CE", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CF - OBJETO INTERNACIONAL COLIS.
   */
  CF("CF", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CG - OBJETO INTERNACIONAL COLIS.
   */
  CG("CG", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CH - OBJETO INTERNACIONAL COLIS.
   */
  CH("CH", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CI - OBJETO INTERNACIONAL COLIS.
   */
  CI("CI", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CJ - OBJETO INTERNACIONAL COLIS.
   */
  CJ("CJ", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CK - OBJETO INTERNACIONAL COLIS.
   */
  CK("CK", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CL - OBJETO INTERNACIONAL COLIS.
   */
  CL("CL", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CM - OBJETO INTERNACIONAL COLIS.
   */
  CM("CM", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CN - OBJETO INTERNACIONAL COLIS.
   */
  CN("CN", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CO - OBJETO INTERNACIONAL COLIS.
   */
  CO("CO", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CP - OBJETO INTERNACIONAL COLIS.
   */
  CP("CP", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CQ - OBJETO INTERNACIONAL COLIS.
   */
  CQ("CQ", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CR - OBJETO INTERNACIONAL COLIS.
   */
  CR("CR", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CS - OBJETO INTERNACIONAL COLIS.
   */
  CS("CS", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CT - OBJETO INTERNACIONAL COLIS.
   */
  CT("CT", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CU - OBJETO INTERNACIONAL COLIS.
   */
  CU("CU", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CV - OBJETO INTERNACIONAL COLIS.
   */
  CV("CV", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CW - OBJETO INTERNACIONAL COLIS.
   */
  CW("CW", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CX - OBJETO INTERNACIONAL COLIS.
   */
  CX("CX", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CY - OBJETO INTERNACIONAL COLIS.
   */
  CY("CY", "OBJETO INTERNACIONAL COLIS"),
  /**
   * CZ - OBJETO INTERNACIONAL COLIS.
   */
  CZ("CZ", "OBJETO INTERNACIONAL COLIS"),
  /**
   * DA - ENCOMENDA SEDEX C/ AR DIGITAL.
   */
  DA("DA", "ENCOMENDA SEDEX C/ AR DIGITAL"),
  /**
   * DB - REMESSA EXPRESSA C/ AR DIGITAL-BRADESCO.
   */
  DB("DB", "REMESSA EXPRESSA C/ AR DIGITAL-BRADESCO"),
  /**
   * DC - REMESSA EXPRESSA (ORGAO TRANSITO).
   */
  DC("DC", "REMESSA EXPRESSA (ORGAO TRANSITO)"),
  /**
   * DD - DEVOLUÇÃO DE DOCUMENTOS.
   */
  DD("DD", "DEVOLUÇÃO DE DOCUMENTOS"),
  /**
   * DE - REMESSA EXPRESSA C/ AR DIGITAL.
   */
  DE("DE", "REMESSA EXPRESSA C/ AR DIGITAL"),
  /**
   * DF - ENCOMENDA SEDEX (ETIQ LOGICA).
   */
  DF("DF", "ENCOMENDA SEDEX (ETIQ LOGICA)"),
  /**
   * DG - ENCOMENDA SEDEX (ETIQ LOGICA).
   */
  DG("DG", "ENCOMENDA SEDEX (ETIQ LOGICA)"),
  /**
   * DI - REM EXPRES COM AR DIGITAL ITAU.
   */
  DI("DI", "REM EXPRES COM AR DIGITAL ITAU"),
  /**
   * DJ - ENCOMENDA SEDEX.
   */
  DJ("DJ", "ENCOMENDA SEDEX"),
  /**
   * DK - SEDEX EXTRA GRANDE.
   */
  DK("DK", "SEDEX EXTRA GRANDE"),
  /**
   * DL - SEDEX LÓGICO.
   */
  DL("DL", "SEDEX LÓGICO"),
  /**
   * DM - ENCOMENDA SEDEX.
   */
  DM("DM", "ENCOMENDA SEDEX"),
  /**
   * DN - ENCOMENDA SEDEX.
   */
  DN("DN", "ENCOMENDA SEDEX"),
  /**
   * DO - REM EXPRES COM AR DIGITAL ITAU UNIBANCO.
   */
  DO("DO", "REM EXPRES COM AR DIGITAL ITAU UNIBANCO"),
  /**
   * DP - SEDEX PAGAMENTO ENTREGA.
   */
  DP("DP", "SEDEX PAGAMENTO ENTREGA"),
  /**
   * DQ - REM EXPRES COM AR DIGITAL BRADESCO.
   */
  DQ("DQ", "REM EXPRES COM AR DIGITAL BRADESCO"),
  /**
   * DR - REM EXPRES COM AR DIGITAL SANTANDER.
   */
  DR("DR", "REM EXPRES COM AR DIGITAL SANTANDER"),
  /**
   * DS - REM EXPRES COM AR DIGITAL SANTANDER.
   */
  DS("DS", "REM EXPRES COM AR DIGITAL SANTANDER"),
  /**
   * DT - REMESSA ECON.SEG.TRANSITO C/AR DIGITAL.
   */
  DT("DT", "REMESSA ECON.SEG.TRANSITO C/AR DIGITAL"),
  /**
   * DU - ENCOMENDA SEDEX.
   */
  DU("DU", "ENCOMENDA SEDEX"),
  /**
   * DV - SEDEX COM AR DIGITAL.
   */
  DV("DV", "SEDEX COM AR DIGITAL"),
  /**
   * DW - ENCOMENDA SEDEX (ETIQ LÓGICA).
   */
  DW("DW", "ENCOMENDA SEDEX (ETIQ LÓGICA)"),
  /**
   * DX - SEDEX 10 LÓGICO.
   */
  DX("DX", "SEDEX 10 LÓGICO"),
  /**
   * DY - ENCOMENDA SEDEX (ETIQ FÍSICA).
   */
  DY("DY", "ENCOMENDA SEDEX (ETIQ FÍSICA)"),
  /**
   * DZ - ENCOMENDA SEDEX (ETIQ LOGICA).
   */
  DZ("DZ", "ENCOMENDA SEDEX (ETIQ LOGICA)"),
  /**
   * EA - OBJETO INTERNACIONAL EMS.
   */
  EA("EA", "OBJETO INTERNACIONAL EMS"),
  /**
   * EB - OBJETO INTERNACIONAL EMS.
   */
  EB("EB", "OBJETO INTERNACIONAL EMS"),
  /**
   * EC - ENCOMENDA PAC.
   */
  EC("EC", "ENCOMENDA PAC"),
  /**
   * ED - OBJETO INTERNACIONAL PACKET EXPRESS.
   */
  ED("ED", "OBJETO INTERNACIONAL PACKET EXPRESS"),
  /**
   * EE - OBJETO INTERNACIONAL EMS.
   */
  EE("EE", "OBJETO INTERNACIONAL EMS"),
  /**
   * EF - OBJETO INTERNACIONAL EMS.
   */
  EF("EF", "OBJETO INTERNACIONAL EMS"),
  /**
   * EG - OBJETO INTERNACIONAL EMS.
   */
  EG("EG", "OBJETO INTERNACIONAL EMS"),
  /**
   * EH - OBJETO INTERNACIONAL EMS.
   */
  EH("EH", "OBJETO INTERNACIONAL EMS"),
  /**
   * EI - OBJETO INTERNACIONAL EMS.
   */
  EI("EI", "OBJETO INTERNACIONAL EMS"),
  /**
   * EJ - OBJETO INTERNACIONAL EMS.
   */
  EJ("EJ", "OBJETO INTERNACIONAL EMS"),
  /**
   * EK - OBJETO INTERNACIONAL EMS.
   */
  EK("EK", "OBJETO INTERNACIONAL EMS"),
  /**
   * EL - OBJETO INTERNACIONAL EMS.
   */
  EL("EL", "OBJETO INTERNACIONAL EMS"),
  /**
   * EM - SEDEX MUNDI.
   */
  EM("EM", "SEDEX MUNDI"),
  /**
   * EN - OBJETO INTERNACIONAL EMS.
   */
  EN("EN", "OBJETO INTERNACIONAL EMS"),
  /**
   * EO - OBJETO INTERNACIONAL EMS.
   */
  EO("EO", "OBJETO INTERNACIONAL EMS"),
  /**
   * EP - OBJETO INTERNACIONAL EMS.
   */
  EP("EP", "OBJETO INTERNACIONAL EMS"),
  /**
   * EQ - ENCOMENDA SERVIÇO NÃO EXPRESSA ECT.
   */
  EQ("EQ", "ENCOMENDA SERVIÇO NÃO EXPRESSA ECT"),
  /**
   * ER - REGISTRADO.
   */
  ER("ER", "REGISTRADO"),
  /**
   * ES - OBJETO INTERNACIONAL EMS.
   */
  ES("ES", "OBJETO INTERNACIONAL EMS"),
  /**
   * ET - OBJETO INTERNACIONAL EMS.
   */
  ET("ET", "OBJETO INTERNACIONAL EMS"),
  /**
   * EU - OBJETO INTERNACIONAL EMS.
   */
  EU("EU", "OBJETO INTERNACIONAL EMS"),
  /**
   * EV - OBJETO INTERNACIONAL EMS.
   */
  EV("EV", "OBJETO INTERNACIONAL EMS"),
  /**
   * EW - OBJETO INTERNACIONAL EMS.
   */
  EW("EW", "OBJETO INTERNACIONAL EMS"),
  /**
   * EX - OBJETO INTERNACIONAL EMS.
   */
  EX("EX", "OBJETO INTERNACIONAL EMS"),
  /**
   * EY - OBJETO INTERNACIONAL EMS.
   */
  EY("EY", "OBJETO INTERNACIONAL EMS"),
  /**
   * EZ - OBJETO INTERNACIONAL EMS.
   */
  EZ("EZ", "OBJETO INTERNACIONAL EMS"),
  /**
   * FA - FAC REGISTRADO.
   */
  FA("FA", "FAC REGISTRADO"),
  /**
   * FB - FAC REGISTRADO.
   */
  FB("FB", "FAC REGISTRADO"),
  /**
   * FC - FAC REGISTRADO (5 DIAS).
   */
  FC("FC", "FAC REGISTRADO (5 DIAS)"),
  /**
   * FD - FAC REGISTRADO (10 DIAS).
   */
  FD("FD", "FAC REGISTRADO (10 DIAS)"),
  /**
   * FE - ENCOMENDA FNDE.
   */
  FE("FE", "ENCOMENDA FNDE"),
  /**
   * FF - REGISTRADO DETRAN.
   */
  FF("FF", "REGISTRADO DETRAN"),
  /**
   * FH - FAC REGISTRADO C/ AR DIGITAL.
   */
  FH("FH", "FAC REGISTRADO C/ AR DIGITAL"),
  /**
   * FJ - REMESSA ECONÔMICA C/ AR DIGITAL.
   */
  FJ("FJ", "REMESSA ECONÔMICA C/ AR DIGITAL"),
  /**
   * FM - FAC REGISTRADO (MONITORADO).
   */
  FM("FM", "FAC REGISTRADO (MONITORADO)"),
  /**
   * FR - FAC REGISTRADO.
   */
  FR("FR", "FAC REGISTRADO"),
  /**
   * IA - INTEGRADA AVULSA.
   */
  IA("IA", "INTEGRADA AVULSA"),
  /**
   * IC - INTEGRADA A COBRAR.
   */
  IC("IC", "INTEGRADA A COBRAR"),
  /**
   * ID - INTEGRADA DEVOLUCAO DE DOCUMENTO.
   */
  ID("ID", "INTEGRADA DEVOLUCAO DE DOCUMENTO"),
  /**
   * IE - INTEGRADA ESPECIAL.
   */
  IE("IE", "INTEGRADA ESPECIAL"),
  /**
   * IF - CPF.
   */
  IF("IF", "CPF"),
  /**
   * II - INTEGRADA INTERNO.
   */
  II("II", "INTEGRADA INTERNO"),
  /**
   * IK - INTEGRADA COM COLETA SIMULTANEA.
   */
  IK("IK", "INTEGRADA COM COLETA SIMULTANEA"),
  /**
   * IM - INTEGRADA MEDICAMENTOS.
   */
  IM("IM", "INTEGRADA MEDICAMENTOS"),
  /**
   * IN - OBJ DE CORRESP E EMS REC EXTERIOR.
   */
  IN("IN", "OBJ DE CORRESP E EMS REC EXTERIOR"),
  /**
   * IP - INTEGRADA PROGRAMADA.
   */
  IP("IP", "INTEGRADA PROGRAMADA"),
  /**
   * IR - IMPRESSO REGISTRADO.
   */
  IR("IR", "IMPRESSO REGISTRADO"),
  /**
   * IS - INTEGRADA STANDARD.
   */
  IS("IS", "INTEGRADA STANDARD"),
  /**
   * IT - INTEGRADA TERMOLÁBIL.
   */
  IT("IT", "INTEGRADA TERMOLÁBIL"),
  /**
   * IU - INTEGRADA URGENTE.
   */
  IU("IU", "INTEGRADA URGENTE"),
  /**
   * IX - EDEI ENCOMENDA EXPRESSA.
   */
  IX("IX", "EDEI ENCOMENDA EXPRESSA"),
  /**
   * JA - REMESSA ECONOMICA C/AR DIGITAL.
   */
  JA("JA", "REMESSA ECONOMICA C/AR DIGITAL"),
  /**
   * JB - REMESSA ECONOMICA C/AR DIGITAL.
   */
  JB("JB", "REMESSA ECONOMICA C/AR DIGITAL"),
  /**
   * JC - REMESSA ECONOMICA C/AR DIGITAL.
   */
  JC("JC", "REMESSA ECONOMICA C/AR DIGITAL"),
  /**
   * JD - REMESSA ECONOMICA S/AR DIGITAL.
   */
  JD("JD", "REMESSA ECONOMICA S/AR DIGITAL"),
  /**
   * JE - REMESSA ECONOMICA C/AR DIGITAL.
   */
  JE("JE", "REMESSA ECONOMICA C/AR DIGITAL"),
  /**
   * JF - REMESSA ECONOMICA C/AR DIGITAL.
   */
  JF("JF", "REMESSA ECONOMICA C/AR DIGITAL"),
  /**
   * JG - REGISTRADO PRIORITÁRIO.
   */
  JG("JG", "REGISTRADO PRIORITÁRIO"),
  /**
   * JH - REGISTRADO PRIORITÁRIO.
   */
  JH("JH", "REGISTRADO PRIORITÁRIO"),
  /**
   * JI - REMESSA ECONOMICA S/AR DIGITAL.
   */
  JI("JI", "REMESSA ECONOMICA S/AR DIGITAL"),
  /**
   * JJ - REGISTRADO JUSTIÇA.
   */
  JJ("JJ", "REGISTRADO JUSTIÇA"),
  /**
   * JK - REMESSA ECONÔMICA S/AR DIGITAL.
   */
  JK("JK", "REMESSA ECONÔMICA S/AR DIGITAL"),
  /**
   * JL - REGISTRADO LÓGICO.
   */
  JL("JL", "REGISTRADO LÓGICO"),
  /**
   * JM - MALA DIRETA POSTAL ESPECIAL.
   */
  JM("JM", "MALA DIRETA POSTAL ESPECIAL"),
  /**
   * JN - MALA DIRETA POSTAL ESPECIAL.
   */
  JN("JN", "MALA DIRETA POSTAL ESPECIAL"),
  /**
   * JO - REGISTRADO PRIORITÁRIO.
   */
  JO("JO", "REGISTRADO PRIORITÁRIO"),
  /**
   * JP - OBJETO RECEITA FEDERAL (EXCLUSIVO).
   */
  JP("JP", "OBJETO RECEITA FEDERAL (EXCLUSIVO)"),
  /**
   * JQ - REMESSA ECONOMICA C/AR DIGITAL.
   */
  JQ("JQ", "REMESSA ECONOMICA C/AR DIGITAL"),
  /**
   * JR - REGISTRADO PRIORITÁRIO.
   */
  JR("JR", "REGISTRADO PRIORITÁRIO"),
  /**
   * JS - REGISTRADO LÓGICO.
   */
  JS("JS", "REGISTRADO LÓGICO"),
  /**
   * JT - REGISTRADO URGENTE.
   */
  JT("JT", "REGISTRADO URGENTE"),
  /**
   * JU - ETIQUETA FÍS REGIST URG.
   */
  JU("JU", "ETIQUETA FÍS REGIST URG"),
  /**
   * JV - REMESSA ECONÔMICA C/AR DIGITAL.
   */
  JV("JV", "REMESSA ECONÔMICA C/AR DIGITAL"),
  /**
   * JW - CARTA COMERCIAL A FATURAR (5 DIAS).
   */
  JW("JW", "CARTA COMERCIAL A FATURAR (5 DIAS)"),
  /**
   * JX - CARTA COMERCIAL A FATURAR (10 DIAS).
   */
  JX("JX", "CARTA COMERCIAL A FATURAR (10 DIAS)"),
  /**
   * JY - REMESSA ECONOMICA (5 DIAS).
   */
  JY("JY", "REMESSA ECONOMICA (5 DIAS)"),
  /**
   * JZ - REMESSA ECONOMICA (10 DIAS).
   */
  JZ("JZ", "REMESSA ECONOMICA (10 DIAS)"),
  /**
   * LA - LOGÍSTICA REVERSA SIMULTÂNEA SEDEX.
   */
  LA("LA", "LOGÍSTICA REVERSA SIMULTÂNEA SEDEX"),
  /**
   * LB - LOGÍSTICA REVERSA SIMULTÂNEA SEDEX.
   */
  LB("LB", "LOGÍSTICA REVERSA SIMULTÂNEA SEDEX"),
  /**
   * LC - OBJETO INTERNACIONAL PRIME.
   */
  LC("LC", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LD - OBJETO INTERNACIONAL PRIME.
   */
  LD("LD", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LE - LOGÍSTICA REVERSA ECONOMICA.
   */
  LE("LE", "LOGÍSTICA REVERSA ECONOMICA"),
  /**
   * LF - OBJETO INTERNACIONAL PRIME.
   */
  LF("LF", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LG - OBJETO INTERNACIONAL PRIME.
   */
  LG("LG", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LH - OBJETO INTERNACIONAL PRIME.
   */
  LH("LH", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LI - OBJETO INTERNACIONAL PRIME.
   */
  LI("LI", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LJ - OBJETO INTERNACIONAL PRIME.
   */
  LJ("LJ", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LK - OBJETO INTERNACIONAL PRIME.
   */
  LK("LK", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LL - OBJETO INTERNACIONAL PRIME.
   */
  LL("LL", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LM - OBJETO INTERNACIONAL PRIME.
   */
  LM("LM", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LN - OBJETO INTERNACIONAL PRIME.
   */
  LN("LN", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LP - LOGÍSTICA REVERSA SIMULTÂNEA PAC.
   */
  LP("LP", "LOGÍSTICA REVERSA SIMULTÂNEA PAC"),
  /**
   * LQ - OBJETO INTERNACIONAL PRIME.
   */
  LQ("LQ", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LS - LOGISTICA REVERSA SEDEX.
   */
  LS("LS", "LOGISTICA REVERSA SEDEX"),
  /**
   * LV - LOGISTICA REVERSA EXPRESSA.
   */
  LV("LV", "LOGISTICA REVERSA EXPRESSA"),
  /**
   * LW - OBJETO INTERNACIONAL PRIME.
   */
  LW("LW", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LX - OBJETO INTERNACIONAL PACKET ECONOMIC.
   */
  LX("LX", "OBJETO INTERNACIONAL PACKET ECONOMIC"),
  /**
   * LY - OBJETO INTERNACIONAL PRIME.
   */
  LY("LY", "OBJETO INTERNACIONAL PRIME"),
  /**
   * LZ - OBJETO INTERNACIONAL PRIME.
   */
  LZ("LZ", "OBJETO INTERNACIONAL PRIME"),
  /**
   * MA - TELEGRAMA - SERVICOS ADICIONAIS.
   */
  MA("MA", "TELEGRAMA - SERVICOS ADICIONAIS"),
  /**
   * MB - TELEGRAMA DE BALCAO.
   */
  MB("MB", "TELEGRAMA DE BALCAO"),
  /**
   * MC - TELEGRAMA FONADO.
   */
  MC("MC", "TELEGRAMA FONADO"),
  /**
   * MD - MAQUINA DE FRANQUEAR (LOGICA).
   */
  MD("MD", "MAQUINA DE FRANQUEAR (LOGICA)"),
  /**
   * ME - TELEGRAMA.
   */
  ME("ME", "TELEGRAMA"),
  /**
   * MF - TELEGRAMA FONADO.
   */
  MF("MF", "TELEGRAMA FONADO"),
  /**
   * MH - CARTA VIA INTERNET.
   */
  MH("MH", "CARTA VIA INTERNET"),
  /**
   * MK - TELEGRAMA CORPORATIVO.
   */
  MK("MK", "TELEGRAMA CORPORATIVO"),
  /**
   * MM - TELEGRAMA GRANDES CLIENTES.
   */
  MM("MM", "TELEGRAMA GRANDES CLIENTES"),
  /**
   * MP - TELEGRAMA PRÉ-PAGO.
   */
  MP("MP", "TELEGRAMA PRÉ-PAGO"),
  /**
   * MS - ENCOMENDA SAUDE.
   */
  MS("MS", "ENCOMENDA SAUDE"),
  /**
   * MT - TELEGRAMA VIA TELEMAIL.
   */
  MT("MT", "TELEGRAMA VIA TELEMAIL"),
  /**
   * MY - TELEGRAMA INTERNACIONAL ENTRANTE.
   */
  MY("MY", "TELEGRAMA INTERNACIONAL ENTRANTE"),
  /**
   * MZ - TELEGRAMA VIA CORREIOS ON LINE.
   */
  MZ("MZ", "TELEGRAMA VIA CORREIOS ON LINE"),
  /**
   * NE - TELE SENA RESGATADA.
   */
  NE("NE", "TELE SENA RESGATADA"),
  /**
   * NX - EDEI ENCOMENDA NAO URGENTE.
   */
  NX("NX", "EDEI ENCOMENDA NAO URGENTE"),
  /**
   * OA - ENCOMENDA SEDEX (ETIQ LOGICA).
   */
  OA("OA", "ENCOMENDA SEDEX (ETIQ LOGICA)"),
  /**
   * OB - ENCOMENDA SEDEX (ETIQ LOGICA).
   */
  OB("OB", "ENCOMENDA SEDEX (ETIQ LOGICA)"),
  /**
   * OC - ENCOMENDA SEDEX (ETIQ LOGICA).
   */
  OC("OC", "ENCOMENDA SEDEX (ETIQ LOGICA)"),
  /**
   * OD - ENCOMENDA SEDEX (ETIQ FÍSICA).
   */
  OD("OD", "ENCOMENDA SEDEX (ETIQ FÍSICA)"),
  /**
   * OF - ETIQUETA LÓGICA SEDEX.
   */
  OF("OF", "ETIQUETA LÓGICA SEDEX"),
  /**
   * OG - ETIQUETA LÓGICA SEDEX.
   */
  OG("OG", "ETIQUETA LÓGICA SEDEX"),
  /**
   * OH - ETIQUETA LÓGICA SEDEX.
   */
  OH("OH", "ETIQUETA LÓGICA SEDEX"),
  /**
   * OI - ETIQUETA LOGICA SEDEX.
   */
  OI("OI", "ETIQUETA LOGICA SEDEX"),
  /**
   * PA - PASSAPORTE.
   */
  PA("PA", "PASSAPORTE"),
  /**
   * PB - ENCOMENDA PAC - NÃO URGENTE.
   */
  PB("PB", "ENCOMENDA PAC - NÃO URGENTE"),
  /**
   * PC - ENCOMENDA PAC A COBRAR.
   */
  PC("PC", "ENCOMENDA PAC A COBRAR"),
  /**
   * PD - ENCOMENDA PAC.
   */
  PD("PD", "ENCOMENDA PAC"),
  /**
   * PE - ENCOMENDA PAC (ETIQUETA FISICA).
   */
  PE("PE", "ENCOMENDA PAC (ETIQUETA FISICA)"),
  /**
   * PF - PASSAPORTE.
   */
  PF("PF", "PASSAPORTE"),
  /**
   * PG - ENCOMENDA PAC (ETIQUETA FISICA).
   */
  PG("PG", "ENCOMENDA PAC (ETIQUETA FISICA)"),
  /**
   * PH - ENCOMENDA PAC (ETIQUETA LOGICA).
   */
  PH("PH", "ENCOMENDA PAC (ETIQUETA LOGICA)"),
  /**
   * PI - ENCOMENDA PAC.
   */
  PI("PI", "ENCOMENDA PAC"),
  /**
   * PJ - ENCOMENDA PAC.
   */
  PJ("PJ", "ENCOMENDA PAC"),
  /**
   * PK - PAC EXTRA GRANDE.
   */
  PK("PK", "PAC EXTRA GRANDE"),
  /**
   * PL - ENCOMENDA PAC.
   */
  PL("PL", "ENCOMENDA PAC"),
  /**
   * PM - ENCOMENDA PAC (ETIQ FÍSICA).
   */
  PM("PM", "ENCOMENDA PAC (ETIQ FÍSICA)"),
  /**
   * PN - ENCOMENDA PAC (ETIQ LOGICA).
   */
  PN("PN", "ENCOMENDA PAC (ETIQ LOGICA)"),
  /**
   * PO - ENCOMENDA PAC (ETIQ LOGICA).
   */
  PO("PO", "ENCOMENDA PAC (ETIQ LOGICA)"),
  /**
   * PP - ETIQUETA LÓGICA PAC.
   */
  PP("PP", "ETIQUETA LÓGICA PAC"),
  /**
   * PQ - ETIQUETA LOGICA PAC MINI.
   */
  PQ("PQ", "ETIQUETA LOGICA PAC MINI"),
  /**
   * PR - REEMBOLSO POSTAL - CLIENTE AVULSO.
   */
  PR("PR", "REEMBOLSO POSTAL - CLIENTE AVULSO"),
  /**
   * PS - ETIQUETA LÓGICA PAC.
   */
  PS("PS", "ETIQUETA LÓGICA PAC"),
  /**
   * PT - ETIQUETA LÓGICA PAC.
   */
  PT("PT", "ETIQUETA LÓGICA PAC"),
  /**
   * PU - ETIQUETA LÓGICA PAC.
   */
  PU("PU", "ETIQUETA LÓGICA PAC"),
  /**
   * PV - ETIQUETA LÓGICA PAC ADMINISTRATIVO.
   */
  PV("PV", "ETIQUETA LÓGICA PAC ADMINISTRATIVO"),
  /**
   * PW - ETIQUETA LÓGICA PAC.
   */
  PW("PW", "ETIQUETA LÓGICA PAC"),
  /**
   * PX - ETIQUETA LÓGICA PAC.
   */
  PX("PX", "ETIQUETA LÓGICA PAC"),
  /**
   * RA - REGISTRADO PRIORITÁRIO.
   */
  RA("RA", "REGISTRADO PRIORITÁRIO"),
  /**
   * RB - CARTA REGISTRADA.
   */
  RB("RB", "CARTA REGISTRADA"),
  /**
   * RC - CARTA REGISTRADA COM VALOR DECLARADO.
   */
  RC("RC", "CARTA REGISTRADA COM VALOR DECLARADO"),
  /**
   * RD - REMESSA ECONOMICA DETRAN.
   */
  RD("RD", "REMESSA ECONOMICA DETRAN"),
  /**
   * RE - MALA DIRETA POSTAL ESPECIAL.
   */
  RE("RE", "MALA DIRETA POSTAL ESPECIAL"),
  /**
   * RF - OBJETO DA RECEITA FEDERAL.
   */
  RF("RF", "OBJETO DA RECEITA FEDERAL"),
  /**
   * RG - REGISTRADO DO SISTEMA SARA.
   */
  RG("RG", "REGISTRADO DO SISTEMA SARA"),
  /**
   * RH - REGISTRADO COM AR DIGITAL.
   */
  RH("RH", "REGISTRADO COM AR DIGITAL"),
  /**
   * RI - REGISTRADO PRIORITÁRIO INTERNACIONAL.
   */
  RI("RI", "REGISTRADO PRIORITÁRIO INTERNACIONAL"),
  /**
   * RJ - REGISTRADO AGÊNCIA.
   */
  RJ("RJ", "REGISTRADO AGÊNCIA"),
  /**
   * RK - REGISTRADO AGÊNCIA.
   */
  RK("RK", "REGISTRADO AGÊNCIA"),
  /**
   * RL - REGISTRADO LÓGICO.
   */
  RL("RL", "REGISTRADO LÓGICO"),
  /**
   * RM - REGISTRADO AGÊNCIA.
   */
  RM("RM", "REGISTRADO AGÊNCIA"),
  /**
   * RN - REGISTRADO AGÊNCIA.
   */
  RN("RN", "REGISTRADO AGÊNCIA"),
  /**
   * RO - REGISTRADO AGÊNCIA.
   */
  RO("RO", "REGISTRADO AGÊNCIA"),
  /**
   * RP - REEMBOLSO POSTAL - CLIENTE INSCRITO.
   */
  RP("RP", "REEMBOLSO POSTAL - CLIENTE INSCRITO"),
  /**
   * RQ - REGISTRADO AGÊNCIA.
   */
  RQ("RQ", "REGISTRADO AGÊNCIA"),
  /**
   * RR - REGISTRADO INTERNACIONAL.
   */
  RR("RR", "REGISTRADO INTERNACIONAL"),
  /**
   * RS - REM ECON ORG TRANSITO COM OU SEM AR.
   */
  RS("RS", "REM ECON ORG TRANSITO COM OU SEM AR"),
  /**
   * RT - REM ECON TALAO/CARTAO SEM AR DIGITA.
   */
  RT("RT", "REM ECON TALAO/CARTAO SEM AR DIGITA"),
  /**
   * RU - REGISTRADO SERVIÇO ECT.
   */
  RU("RU", "REGISTRADO SERVIÇO ECT"),
  /**
   * RV - REM ECON CRLV/CRV/CNH COM AR DIGITAL.
   */
  RV("RV", "REM ECON CRLV/CRV/CNH COM AR DIGITAL"),
  /**
   * RW - REGISTRADO INTERNACIONAL.
   */
  RW("RW", "REGISTRADO INTERNACIONAL"),
  /**
   * RX - REGISTRADO INTERNACIONAL.
   */
  RX("RX", "REGISTRADO INTERNACIONAL"),
  /**
   * RY - REM ECON TALAO/CARTAO COM AR DIGITAL.
   */
  RY("RY", "REM ECON TALAO/CARTAO COM AR DIGITAL"),
  /**
   * RZ - REGISTRADO.
   */
  RZ("RZ", "REGISTRADO"),
  /**
   * SA - ETIQUETA SEDEX AGÊNCIA.
   */
  SA("SA", "ETIQUETA SEDEX AGÊNCIA"),
  /**
   * SB - SEDEX 10.
   */
  SB("SB", "SEDEX 10"),
  /**
   * SC - SEDEX A COBRAR.
   */
  SC("SC", "SEDEX A COBRAR"),
  /**
   * SD - REMESSA EXPRESSA DETRAN.
   */
  SD("SD", "REMESSA EXPRESSA DETRAN"),
  /**
   * SE - ENCOMENDA SEDEX.
   */
  SE("SE", "ENCOMENDA SEDEX"),
  /**
   * SF - SEDEX AGENCIA.
   */
  SF("SF", "SEDEX AGENCIA"),
  /**
   * SG - SEDEX DO SISTEMA SARA.
   */
  SG("SG", "SEDEX DO SISTEMA SARA"),
  /**
   * SH - SEDEX COM AR DIGITAL.
   */
  SH("SH", "SEDEX COM AR DIGITAL"),
  /**
   * SI - SEDEX AGÊNCIA.
   */
  SI("SI", "SEDEX AGÊNCIA"),
  /**
   * SJ - SEDEX HOJE.
   */
  SJ("SJ", "SEDEX HOJE"),
  /**
   * SK - SEDEX AGÊNCIA.
   */
  SK("SK", "SEDEX AGÊNCIA"),
  /**
   * SL - SEDEX LÓGICO.
   */
  SL("SL", "SEDEX LÓGICO"),
  /**
   * SM - SEDEX 12.
   */
  SM("SM", "SEDEX 12"),
  /**
   * SN - SEDEX AGÊNCIA.
   */
  SN("SN", "SEDEX AGÊNCIA"),
  /**
   * SO - SEDEX AGÊNCIA.
   */
  SO("SO", "SEDEX AGÊNCIA"),
  /**
   * SP - SEDEX PRÉ-FRANQUEADO.
   */
  SP("SP", "SEDEX PRÉ-FRANQUEADO"),
  /**
   * SQ - SEDEX.
   */
  SQ("SQ", "SEDEX"),
  /**
   * SR - SEDEX.
   */
  SR("SR", "SEDEX"),
  /**
   * SS - SEDEX FÍSICO.
   */
  SS("SS", "SEDEX FÍSICO"),
  /**
   * ST - REM EXPRES TALAO/CARTAO SEM AR DIGITAL.
   */
  ST("ST", "REM EXPRES TALAO/CARTAO SEM AR DIGITAL"),
  /**
   * SU - ENCOMENDA SERVIÇO EXPRESSA ECT.
   */
  SU("SU", "ENCOMENDA SERVIÇO EXPRESSA ECT"),
  /**
   * SV - REM EXPRES CRLV/CRV/CNH COM AR DIGITAL.
   */
  SV("SV", "REM EXPRES CRLV/CRV/CNH COM AR DIGITAL"),
  /**
   * SW - ENCOMENDA SEDEX.
   */
  SW("SW", "ENCOMENDA SEDEX"),
  /**
   * SX - SEDEX 10.
   */
  SX("SX", "SEDEX 10"),
  /**
   * SY - REM EXPRES TALAO/CARTAO COM AR DIGITAL.
   */
  SY("SY", "REM EXPRES TALAO/CARTAO COM AR DIGITAL"),
  /**
   * SZ - SEDEX AGÊNCIA.
   */
  SZ("SZ", "SEDEX AGÊNCIA"),
  /**
   * TC - TESTE (OBJETO PARA TREINAMENTO).
   */
  TC("TC", "TESTE (OBJETO PARA TREINAMENTO)"),
  /**
   * TE - TESTE (OBJETO PARA TREINAMENTO).
   */
  TE("TE", "TESTE (OBJETO PARA TREINAMENTO)"),
  /**
   * TR - OBJETO TREINAMENTO - NÃO GERA PRÉ-ALERTA.
   */
  TR("TR", "OBJETO TREINAMENTO - NÃO GERA PRÉ-ALERTA"),
  /**
   * TS - TESTE (OBJETO PARA TREINAMENTO).
   */
  TS("TS", "TESTE (OBJETO PARA TREINAMENTO)"),
  /**
   * VA - OBJETO INTERNACIONAL COM VALOR DECLARADO.
   */
  VA("VA", "OBJETO INTERNACIONAL COM VALOR DECLARADO"),
  /**
   * VC - OBJETO INTERNACIONAL COM VALOR DECLARADO.
   */
  VC("VC", "OBJETO INTERNACIONAL COM VALOR DECLARADO"),
  /**
   * VD - OBJETO INTERNACIONAL COM VALOR DECLARADO.
   */
  VD("VD", "OBJETO INTERNACIONAL COM VALOR DECLARADO"),
  /**
   * VE - OBJETO INTERNACIONAL COM VALOR DECLARADO.
   */
  VE("VE", "OBJETO INTERNACIONAL COM VALOR DECLARADO"),
  /**
   * VF - OBJETO INTERNACIONAL COM VALOR DECLARADO.
   */
  VF("VF", "OBJETO INTERNACIONAL COM VALOR DECLARADO"),
  /**
   * VV - OBJETO INTERNACIONAL COM VALOR DECLARADO.
   */
  VV("VV", "OBJETO INTERNACIONAL COM VALOR DECLARADO"),
  /**
   * XA - AVISO CHEGADA OBJETO INT TRIBUTADO.
   */
  XA("XA", "AVISO CHEGADA OBJETO INT TRIBUTADO"),
  /**
   * XM - SEDEX MUNDI.
   */
  XM("XM", "SEDEX MUNDI"),
  /**
   * XR - OBJETO INTERNACIONAL (PPS TRIBUTADO).
   */
  XR("XR", "OBJETO INTERNACIONAL (PPS TRIBUTADO)"),
  /**
   * XX - OBJETO INTERNACIONAL (PPS TRIBUTADO).
   */
  XX("XX", "OBJETO INTERNACIONAL (PPS TRIBUTADO)"),
  /**
   * Unknown service type.
   */
  UNKNOWN("", "");

  private String mInitials;
  private String mDescription;

  TrackObjectServiceType(String initials, String description) {
    this.mInitials = initials;
    this.mDescription = description;
  }

  /**
   * @return service type initials
   */
  public String getInitials() {
    return mInitials;
  }

  /**
   * @return service type description
   */
  public String getDescription() {
    return mDescription;
  }
}
